### ISSUE TITLE
Can the code be modified to only forward edited messages?

### ISSUE THREAD

**Issue by oscarstv** [radinshayanfar/TGCopyBot#7]
Thank you, I’m trying to do that, don’t know if your code can be the base code for getting that done.

**Comment by radinshayanfar** [comment]
Hi @oscarstv 
TDlib utilizes different [Update](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_update.html) objects. To handle edited messages, you can add a handler for`updateMessageContent` object:
```python
tg.add_update_handler("updateMessageContent", message_edit_handler)
```
where `message_edit_handler` is the function that is called every time a message is edited. Just add it before the last line of the `app.py` (i.e. before `tg.idle()`).

**Comment by oscarstv** [comment]
@radinshayanfar Thank you very much 👍
