### ISSUE TITLE
Messages are not being copied over

### ISSUE THREAD

**Issue by Horuyuki** [radinshayanfar/TGCopyBot#8]
I made an app as was instructed by the link, copied all necessary infos to the env file and logged in with a code.

Then I pasted the source and destination channel which my account is in into the env file and run the command without forking to background:
```
$ sudo docker run --env-file=.env -v td-data:/home/wit/.temp/tgbot/tgfiles radinshayanfar/tgcopybot
[ 2][t 4][xxx][TdDb.cpp:318][#1][!Td]	Got PRAGMA user_version = 13
[ 2][t 4][xxx][AuthDataShared.cpp:107][#1][!Td]	DcId{1} [auth_key_id:xxx][state:OK][created_at: xxx]
[ 2][t 4][xxx][Session.cpp:170][#1][!SessionProxy:1:main]	Generate new session_id xxx for auth key xxx for main DC1
^C[ 2][t 4][xxx][Td.cpp:3764][#1][!Td]	Close Td in state 2
[ 2][t 4][xxx][Td.cpp:3607][#1][!Td]	Have no request actors
[ 2][t 4][xxx][Td.cpp:3510][#1][!Td]	ON_ACTORS_CLOSED
[ 2][t 4][xxx][Td.cpp:3583][#1][!Td]	ON_CLOSED
[ 2][t 4][xxx][Td.cpp:3593][#1][!Td]	Stop Td
```
Closed it with control-C

Can you tell me why nothing is being copied over?

My `.env`
```
######################
# App Configurations #
######################

SOURCE=-11111111111
DESTINATION=-111111111111111
(ones are only meant to replace actual channel number)

###########################
# Telegram Configurations #
###########################

# Your app_id and api_hash obtained from my.telegram.org/apps
API_ID=xxx
API_HASH=xxx

# Your user phone number
PHONE=+1xxxxxxxxxx

# An arbitrary key for app datebase
DB_PASSWORD=xxx
# Where the app stores files
FILES_DIRECTORY=/home/wit/.temp/tgbot/tgfiles

# Proxy (if needed)
PROXY_TYPE= # "proxyTypeMtproto", "proxyTypeHttp" or "proxyTypeSocks5"
PROXY_SERVER=
PROXY_PORT=
```
EDIT:
It actually does forward the messages, but only new ones. Is it possible for it to copy all existing messages from source?

**Comment by oscarstv** [comment]
> I made an app as was instructed by the link, copied all necessary infos to the env file and logged in with a code.
> 
> Then I pasted the source and destination channel which my account is in into the env file and run the command without forking to background:
> 
> ```
> $ sudo docker run --env-file=.env -v td-data:/home/wit/.temp/tgbot/tgfiles radinshayanfar/tgcopybot
> [ 2][t 4][xxx][TdDb.cpp:318][#1][!Td]	Got PRAGMA user_version = 13
> [ 2][t 4][xxx][AuthDataShared.cpp:107][#1][!Td]	DcId{1} [auth_key_id:xxx][state:OK][created_at: xxx]
> [ 2][t 4][xxx][Session.cpp:170][#1][!SessionProxy:1:main]	Generate new session_id xxx for auth key xxx for main DC1
> ^C[ 2][t 4][xxx][Td.cpp:3764][#1][!Td]	Close Td in state 2
> [ 2][t 4][xxx][Td.cpp:3607][#1][!Td]	Have no request actors
> [ 2][t 4][xxx][Td.cpp:3510][#1][!Td]	ON_ACTORS_CLOSED
> [ 2][t 4][xxx][Td.cpp:3583][#1][!Td]	ON_CLOSED
> [ 2][t 4][xxx][Td.cpp:3593][#1][!Td]	Stop Td
> ```
> 
> Closed it with control-C
> 
> Can you tell me why nothing is being copied over?
> 
> My `.env`
> 
> ```
> ######################
> # App Configurations #
> ######################
> 
> SOURCE=-11111111111
> DESTINATION=-111111111111111
> (ones are only meant to replace actual channel number)
> 
> ###########################
> # Telegram Configurations #
> ###########################
> 
> # Your app_id and api_hash obtained from my.telegram.org/apps
> API_ID=xxx
> API_HASH=xxx
> 
> # Your user phone number
> PHONE=+1xxxxxxxxxx
> 
> # An arbitrary key for app datebase
> DB_PASSWORD=xxx
> # Where the app stores files
> FILES_DIRECTORY=/home/wit/.temp/tgbot/tgfiles
> 
> # Proxy (if needed)
> PROXY_TYPE= # "proxyTypeMtproto", "proxyTypeHttp" or "proxyTypeSocks5"
> PROXY_SERVER=
> PROXY_PORT=
> ```
> 
> EDIT: It actually does forward the messages, but only new ones. Is it possible for it to copy all existing messages from source?

Hi, [Horuyuki](https://github.com/Horuyuki), I understand the idea is forwarding messages, but using the copy function, it's not created for copying a whole channel to another one. So, it does what's supposed to.

**Comment by radinshayanfar** [comment]
@oscarstv is right.
I'll close the issue.

**Comment by radinshayanfar** [comment]
@Horuyuki It is worth mentioning that Telegram has some rate limiting policies for sending message. Therefore, depending on the number of messages in the source channel, it may take a long time to copy all messages to a new channel. So, considering Telegram rate limiting policy, it may not be a good idea to implement what you want.
